site_name: DJI Digital FPV System
site_url: https://www.djifpv.ru/
site_author: Stanislav Kremen
site_description: >-
  Здесь хранится базовая информация и накопленный опыт сообщества о цифровой FPV системе от DJI для DIY носителей.

# Repository
repo_name: benmozes/djifpvdocs
repo_url: https://github.com/benmozes/djifpvdocs

theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.ico
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    logo: simple/dji
    annotation: material/lightbulb-alert-outline
  features:
    - content.code.annotate
    - navigation.tabs
    # - navigation.sections
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - announce.dismiss
    - navigation.indexes
    # - navigation.expand
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/djifpvru
extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css
nav:
  - Home: index.md
  - База знаний: 
    - knowledge_base/index.md
    - 'FCC hack': knowledge_base/fcc.md
    - 'Таймлайн': knowledge_base/timeline.md
    - 'Влагозащита': 
      - knowledge_base/coating/index.md
      - 'Caddx Vista/Runcam Link': knowledge_base/coating/coating_vista.md
      - 'o3 Air unit': knowledge_base/coating/coating_o3.md
      - 'o4 Air unit (lite)': knowledge_base/coating/coating_o4.md
  - Очки:
    - goggles/index.md
    - 'DJI FPV Goggles': goggles/v1.md
    - 'DJI FPV Goggles V2': goggles/v2.md
    - 'DJI Goggles 2': goggles/g2.md
    - 'DJI Goggles Integra': goggles/integra.md
    - 'DJI Goggles 3': goggles/g3.md
    - 'DJI Goggles N3': goggles/n3.md
  - Видеопередатчики:
    - vtx/index.md
    - 'DJI Air Unit': vtx/air_unit.md
    - 'DJI Air Unit (lite)/Caddx Vista/Runcam link': vtx/vista.md
    - 'DJI o3 Air Unit': vtx/o3.md
    - 'DJI o4 Air Unit': vtx/o4.md
    - 'DJI o4 Air Unit Pro': vtx/o4pro.md
  - WTFOS:
    - wtfos/index.md
    - 'Совместимость': wtfos/compatibility.md


markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - abbr
  - pymdownx.critic
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - def_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - tables
  - neoteroi.timeline
  - toc:
      permalink: ⚓︎
      title: On this page
      permalink_title: Anchor link to this section for reference
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
watch:
  - includes
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: false
      enable_creation_date: true
      exclude:
          - index.md
      enable_git_follow: true
      enabled: true
      strict: true
  - tags:
      tags_file: tags.md
