site_name: DJI FPV Docs
theme:
  name: material
  favicon: images/favicon.ico
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    logo: simple/dji
    annotation: material/lightbulb-alert-outline
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky 
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - toc.integrate
  hide:
    - toc
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/djifpvru
nav:
  - Knowledge Base:
    - 'DJI FPV': index.md
  - Первое поколение:
    - 'Первое поколение': first_gen/index.md
    - 'Очки': first_gen/goggles/index.md

language: ru
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables