site_name: DJI Digital FPV
site_url: https://www.djifpv.ru/
site_author: Stanislav Kremen
site_description: >-
  Здесь хранится базовая информация и накопленный опыт сообщества о цифровой FPV системе от DJI для DIY носителей.

# Repository
repo_name: benmozes/djifpvdocs
repo_url: https://github.com/benmozes/djifpvdocs
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.ico
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    logo: simple/dji
    annotation: material/lightbulb-alert-outline
    repo: fontawesome/brands/github
    edit: material/pencil-outline
    view: material/eye-outline
  language: ru
  features:
    - content.code.annotate
    - content.action.view
    - content.action.edit
    - navigation.tabs
    # - navigation.sections
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - announce.dismiss
    - navigation.indexes
    # - navigation.expand
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: переключить в светлый режим

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: переключить в темный режим

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: тема в соответствии системной
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/djifpvru
  analytics:
      provider: google
      property: G-G82LVRX450
  consent:
    title: согласие на обработку cookies
    description: >- 
      www.djifpv.ru обрабатывает файлы cookie.
      Они помогают нам делать этот сайт удобнее для пользователей. 
      Продолжая работу с сайтом www.djifpv.ru, вы соглашаетесь с обработкой файлов cookie
      вашего браузера. Однако вы можете запретить обработку некоторых типов файлов cookie в настройках
      вашего браузера либо на странице «Уведомление об
      использовании файлов cookie».
extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css
nav:
  - Home: index.md
  - База знаний: 
    - knowledge_base/index.md
    - 'Совместимость': knowledge_base/compatibility.md
    - 'FCC hack': knowledge_base/fcc.md
    - 'Настройка OSD': knowledge_base/osd.md
    - 'Известные баги': knowledge_base/known_bugs.md
    - 'Влагозащита': 
      - knowledge_base/coating/index.md
      - 'Caddx Vista': knowledge_base/coating/coating_vista.md
      - 'o3 Air unit': knowledge_base/coating/coating_o3.md
      - 'o4 Air unit': knowledge_base/coating/coating_o4.md
    - 'Таймлайн': knowledge_base/timeline.md
    - 'DJI Fly': knowledge_base/dji_fly.md
  - Очки:
    - goggles/index.md
    - 'DJI FPV Goggles': goggles/v1.md
    - 'DJI FPV Goggles V2': goggles/v2.md
    - 'DJI Goggles 2': goggles/g2.md
    - 'DJI Goggles Integra': goggles/integra.md
    - 'DJI Goggles 3': goggles/g3.md
    - 'DJI Goggles N3': goggles/n3.md
  - Видеопередатчики:
    - vtx/index.md
    - 'DJI Air Unit': vtx/air_unit.md
    - 'Caddx Vista': vtx/vista.md
    - 'DJI o3 Air Unit': vtx/o3.md
    - 'DJI o4 Air Unit': vtx/o4.md
    - 'DJI o4 Air Unit Pro': vtx/o4pro.md
  - WTFOS:
    - wtfos/index.md
    - 'Совместимость': wtfos/compatibility.md
  - Новости:
    - blog/index.md


markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - abbr
  - pymdownx.critic
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - def_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - tables
  - neoteroi.timeline
  - toc:
      permalink: ⚓︎
      title: On this page
      permalink_title: Anchor link to this section for reference
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
watch:
  - includes
plugins:
  - search
  - glightbox:
      manual: true
  - git-revision-date-localized:
      type: iso_date
      fallback_to_build_date: false
      enable_creation_date: true
      exclude:
          - index.md
      enable_git_follow: true
      enabled: true
      strict: true
  - tags:
      tags_file: tags.md
      tags: true
      enabled: true
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
        tags_slugify_separator: _
        tags_slugify_format: "tag:{slug}"
  - social:
      cards_layout_options:
        background_color: "#48c9b0"
      enabled: !ENV [CI, false]
  - blog:
      blog_dir: blog
      blog_toc: true
      post_date_format: full
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{categories}/{slug}"
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      post_slugify_separator: _
      post_readtime_words_per_minute: 300
      archive: false
      categories_toc: true

